#pagebreak()
= Discussion
#set heading(numbering: "1.1")

== Interpretation of Results

=== Scalability and Pipeline Structure

The scaling from 7.04 ms to 182.85 ms over a 100$times$ increase in $N$ is driven almost entirely by force evaluation, which accounts for 94–99% of step time. At small $N$ the GPU is underutilised and dispatch overhead dominates; as $N$ grows, the parallel hardware absorbs the increasing traversal workload. The LBVH construction pipeline, by contrast, remains below 1 ms at all tested particle counts, with individual passes approximately constant in $N$. The implication for practitioners is that optimisation efforts should target the BVH traversal shader, not the tree-build pipeline. The direct-versus-tree comparison reinforces this: direct summation is faster at all tested $N$ (reflecting the high degree of GPU parallelism available for its regular, branch-free computation pattern), but the tree path produces 25$times$ lower energy drift at $N = 100000$, making the hierarchical approach essential for physically meaningful long integrations.

=== Abstraction Overhead

The finding that the WebGPU solver outperforms the native Metal baseline (UniSim @unisim) at $N gt.eq 5000$ requires careful interpretation. The advantage does not imply that WebGPU is inherently faster than Metal; rather, the fully GPU-resident LBVH pipeline (radix sort, Karras topology construction, and bottom-up aggregation, all on-device) avoids the CPU–GPU coordination overhead present in UniSim's tree construction approach. The performance gap widens with $N$ (0.48$times$ at $N = 10000$, 0.35$times$ at $N = 100000$), confirming that the benefit is structural rather than incidental. The cross-backend comparison reveals that implementation choice within the same Metal backend produces substantial performance variation: Dawn achieves the lowest per-dispatch overhead (1.47 ms at $N = 1000$) but scales to 274.57 ms at $N = 100000$, while wgpu-native starts higher but scales to 182.85 ms. This is consistent with Maczan's finding that WebGPU implementation choice can produce up to 2.2$times$ variation in per-dispatch cost @maczan2026. The practical implication is that researchers selecting a WebGPU backend for compute-heavy workloads should prefer wgpu-native for large-$N$ throughput and Dawn for low-latency small dispatches.

=== Browser Platform Viability

The browser deployment path adds a fixed overhead of approximately 29 ms per step from the Emscripten asyncify event-loop yield, but this cost does not grow with $N$. At small particle counts (5.1$times$ overhead at $N = 1000$), the asyncify cost dominates; as GPU compute time increases, the fixed cost becomes a diminishing fraction. At $N = 50000$ the browser matches native throughput (67.77 ms vs 67.53 ms), and at $N = 100000$ the overhead is only 1.2$times$. The practical implication is that for scientifically meaningful particle counts ($N gt.eq 10000$), the browser platform approaches native performance, and at $N gt.eq 50000$ the overhead is negligible. This positions WebGPU as viable for interactive, accessible $N$-body simulation without specialised hardware, subject to the 32-bit precision constraint @realitycheck.

=== Numerical Quality

The theta-sweep results ($Delta E \/ |E(0)| approx 1.84$ at all tested $theta$ values) confirm that 32-bit floating-point precision, not the tree approximation or opening angle, is the dominant constraint on numerical fidelity. This means that investing in higher-order multipole expansions or smaller opening angles will not improve energy conservation until 64-bit GPU arithmetic becomes available in WebGPU. For practical use, the leapfrog integrator remains the correct choice: it conserves momentum to within 0.1% over 5,000 steps and maintains stable orbits, consistent with its theoretical properties @springel_2005 @galacticdynamics2nded. The observed Plummer sphere expansion is physical rather than numerical, consistent with known behaviour of finite-$N$ systems with approximate forces @galacticdynamics2nded.

== Comparison with Published Results

Direct comparison with CUDA-based Barnes–Hut implementations is limited by differences in hardware generation, floating-point precision (64-bit in CUDA studies versus 32-bit here), tree topology (octree versus BVH), and opening criteria. Nevertheless, several structural comparisons are informative.

Burtscher and Pingali report CUDA Barnes–Hut performance of approximately 10 billion body-body interactions per second on an NVIDIA GTX 280 @cudabarnes. At $N = 100000$ with $theta = 0.75$, this corresponds to roughly 10 ms per step on 2010-era hardware. The WebGPU implementation requires 182.85 ms per step at the same $N$, reflecting the dominance of the BVH traversal shader (99% of step time) and the irregular memory access patterns of LBVH traversal compared to octree traversal. The comparison across hardware generations and tree topologies is not directly informative, but it indicates that the WebGPU compute shader model can support the complete solver pipeline at large $N$, with throughput determined primarily by traversal efficiency rather than platform overhead.

Gaburov, Bédorf, and Portegies Zwart report tree-construction overhead of approximately 15–25% of total step time in their CUDA octree implementation @bedorf2010. The LBVH construction pipeline in this work accounts for less than 1% of step time (0.96 ms out of 182.85 ms at $N = 100000$), substantially lower than the CUDA reference. This reflects the efficiency of the fully GPU-resident construction method: by performing radix sort, topology construction, and bottom-up aggregation entirely on-device, the LBVH approach eliminates the CPU–GPU transfer costs incurred by CUDA implementations that build the tree on the CPU.

Nyland, Harris, and Prins report direct $O(N^2)$ GPU throughput of approximately 10–30 GFLOP/s for $N$-body problems on contemporary NVIDIA hardware @fastnbody. The WebGPU direct-summation path in this work achieves 4.53 ms per step at $N = 5000$ (equivalent to $N^2 / t approx 5.5 times 10^9$ interactions per second), which is competitive given the integrated GPU architecture of the M2 and the 32-bit precision.

== Limitations

The results should be interpreted in light of several limitations that bound their external validity.

The most significant constraint is that all experiments were conducted on a single Apple M2 system. Although the cross-backend comparison (Group 6) demonstrates that software-side variation across four WebGPU implementations is substantial, all four use the same Metal graphics driver on the same hardware. GPU performance characteristics vary across vendors; the Apple M2 is an integrated GPU with unified memory, which eliminates CPU–GPU transfer costs that would be present on discrete GPU systems, while its compute unit count is modest compared to dedicated NVIDIA or AMD GPUs. The timing results and scaling behaviour reported here may therefore not generalise to other hardware configurations or GPU backends (Vulkan, Direct3D 12).

A second fundamental constraint is the limitation of WebGPU to 32-bit floating-point arithmetic in compute shaders. As the results demonstrate, this single-precision ceiling is the dominant constraint on numerical fidelity, exceeding the effects of the opening angle and timestep size for the configurations tested. The effect is most pronounced at small $N$, where round-off error accumulates over many steps without the statistical averaging that occurs in large-$N$ systems. Relatedly, the force evaluation uses only the monopole term of the multipole expansion; quadrupole and higher-order terms, which are standard in production codes such as GADGET-2 @springel_2005, would reduce the force approximation error at a given $theta$ and potentially allow larger opening angles for the same accuracy target.

On the methodology side, all experiments use a global fixed timestep, whereas production codes commonly employ adaptive individual timestepping that assigns each particle a step proportional to its local dynamical timescale @springel_2005. The absence of adaptive timestepping means that the timestep must be chosen conservatively for the densest region of the simulation, which may be unnecessarily small for the majority of particles. Additionally, energy drift as a quantitative metric is available only for $N lt.eq 5000$, where direct pair summation for potential energy is computationally feasible; for larger $N$, numerical quality is assessed indirectly through kinetic energy trends and momentum conservation.
